function ajouter_sites () {
    ajouter_site("Google","https://www.google.fr/");
    ajouter_site("Ecosia","https://www.ecosia.org/");
    ajouter_site("Bing","https://www.bing.com/");
    ajouter_site("Yahoo","https://yahoo.com");
    ajouter_site("Youtube","https://www.youtube.fr/");
    ajouter_site("Google Traduction","https://translate.google.fr");
    ajouter_site("Gmail","https://mail.google.com");
    ajouter_site("Google Drive","https://drive.google.com");
    ajouter_site("Twitch","https://www.twitch.tv/");
    ajouter_site("Facebook","https://www.facebook.com/");
    ajouter_site("Messenger","https://www.facebook.com/messages");
    ajouter_site("Twitter","https://twitter.com/");
    ajouter_site("Instagram","https://www.instagram.com/");
    ajouter_site("Pinterest","https://www.pinterest.fr/");
    ajouter_site("Netflix","https://www.netflix.com/fr/");
    ajouter_site("Amazon","https://www.amazon.fr/");
    ajouter_site("Ebay","https://www.ebay.fr/");
    ajouter_site("AliExpress","https://fr.aliexpress.com/");
    ajouter_site("Wish","https://www.wish.com/");
    ajouter_site("Wikipédia","https://fr.wikipedia.org/");
    ajouter_site("Github","https://github.com/");
    ajouter_site("Discord","https://discord.com/");
    ajouter_site("Discord <i>Compte personnel</i>","https://discord.com/channels/@me");
    ajouter_site("Guilded","https://www.guilded.gg/");
    ajouter_site("Reddit","https://www.reddit.com/");
    ajouter_site("4chan","https://www.4chan.org/");
    ajouter_site("Google Chrome","https://www.google.com/intl/fr/chrome/");
    ajouter_site("Mozilla Firefox","https://www.mozilla.org/");
    ajouter_site("Kahoot","https://kahoot.it");
    ajouter_site("WolframAlpha","https://www.wolframalpha.com/");
    ajouter_site("OpenClassRoom","https://openclassrooms.com/fr/courses");
    ajouter_site("Emurom","https://emurom.net");
    ajouter_site("Pokepédia","https://www.pokepedia.fr/");
    ajouter_site("Smogon University","https://www.smogon.com/");
    ajouter_site("Pokestrat","https://pokestrat.io/");
    ajouter_site("Pokemon Showdown <i>Site officiel</i>","https://pokemonshowdown.com");
    ajouter_site("Pokemon Showdown <i>Jouer</i>","https://play.pokemonshowdown.com");
    ajouter_site("Riot Games","https://www.riotgames.com/fr");
    ajouter_site("League of Legends","https://na.leagueoflegends.com/fr-fr/");
    ajouter_site("OP.GG","https://euw.op.gg/");
    ajouter_site("OP.GG <i>champions</i>","https://www.op.gg/champion/statistics");
    ajouter_site("Porofessor","https://porofessor.gg/fr");
    ajouter_site("Minecraft Wiki","https://minecraft.fandom.com/fr/wiki/Minecraft_Wiki");
    ajouter_site("Terraria Wiki","https://terraria.fandom.com/fr/wiki/Terraria_Wiki");
    ajouter_site("Dragon Quest Fan","https://www.dragonquest-fan.com/");
    ajouter_site("L'encyclopédie Moga","https://mogapedia.fandom.com/fr/wiki/Monster_Hunter_Wiki/");
    ajouter_site("Kiranico Monster Hunter X","http://mhgen.kiranico.com/");
    ajouter_site("Shadowverse Portal","https://shadowverse-portal.com/cards?format=0&lang=fr");
    ajouter_site("Bandori Party","https://bandori.party/");
    ajouter_site("Wowhead","https://fr.wowhead.com/");
    ajouter_site("Where in Warcraft ?","https://www.kruithne.net/where-in-warcraft/");
    ajouter_site("Summoners War : Sky Arena","https://sw.com2us.com/fr/skyarena");
    ajouter_site("Summoners War Wiki","https://summonerswarskyarena.info/");
    ajouter_site("Youtube convertisseur en MP3","https://mp3y.download/fr/faster-mp3-convert");

    ajouter_site("JsRPG","JsRPG/",true);
    ajouter_site("Dimension the Game","Dimension/",true);
}
